name:                AutomataLePila
version:             0.1.0.0
github:              "jfarizano/AutomataLePila"
license:             MIT
author:              "Juan Ignacio Farizano"
maintainer:          "juanignaciofarizano at google mail dot com"
copyright:           "2022 Juan Ignacio Farizano"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jfarizano/AutomataLePila#readme>

dependencies:
- base >= 4.7 && < 5
- array
- filepath
- mtl
- haskeline
- cmdargs
- exceptions
- text
- prettyprinter
- prettyprinter-ansi-terminal

library:
  source-dirs: src

executables:
  AutomataLePila-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AutomataLePila

tests:
  AutomataLePila-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AutomataLePila
